name: ESP InConcert
favicon: null
layout_spectrum: 0.4333023461513221
typography_spectrum: 0.7472824670840055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9613451648037881
  lightness: 0.6687157130800188
  saturation: 0.44456239929422736
  rhythmicContrast: 0.44057097751647234
purpose: []
