name: ESP InConcert
favicon: null
layout_spectrum: 0.99822
typography_spectrum: 0.60651
title: 'Digital SaaS Platform & Client Services Portal'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#555555'
    - '#b58729'
    - '#800000'
    - '#ff0000'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
