name: ESP InConcert
favicon: null
layout_spectrum: 0.22774012852460146
typography_spectrum: 0.5173975741490722
title: InConcert
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#555555'
    - '#b58729'
    - '#800000'
    - '#ff0000'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
